"""Public immutable batch-processing domain API."""

from docuforge.batch.exceptions import (
    BatchError,
    BatchItemNotFoundError,
    BatchProcessingError,
    InvalidBatchDefinitionError,
    InvalidBatchTransitionError,
)
from docuforge.batch.image import (
    BatchImageCompressRequest,
    BatchImageConvertRequest,
    BatchImageInput,
    BatchImageOutput,
    BatchImageResizeRequest,
    BatchImageResult,
    batch_compress_images,
    batch_convert_images,
    batch_resize_images,
)
from docuforge.batch.models import (
    Batch,
    BatchId,
    BatchItem,
    BatchItemFailure,
    BatchItemId,
    BatchItemRequest,
    BatchItemResult,
    BatchItemStatus,
    BatchRequest,
    BatchStatus,
    BatchSummary,
)

__all__ = [
    "Batch",
    "BatchError",
    "BatchId",
    "BatchImageCompressRequest",
    "BatchImageConvertRequest",
    "BatchImageInput",
    "BatchImageOutput",
    "BatchImageResizeRequest",
    "BatchImageResult",
    "BatchItem",
    "BatchItemFailure",
    "BatchItemId",
    "BatchItemNotFoundError",
    "BatchItemRequest",
    "BatchItemResult",
    "BatchItemStatus",
    "BatchProcessingError",
    "BatchRequest",
    "BatchStatus",
    "BatchSummary",
    "InvalidBatchDefinitionError",
    "InvalidBatchTransitionError",
    "batch_compress_images",
    "batch_convert_images",
    "batch_resize_images",
]
